esphome:
  name: temperature_humidity_sensor

esp32:
  board: esp32dev

# WiFi name and password for connecting to the network
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
# OTA Updates with password protection
ota:
  platform: esphome
  password: !secret ota_password

sensor:
  - platform: dht
    pin: 27
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    # Update intervel in Seconds
    update_interval: 30s
    model: DHT11